# Generated by Django 4.2.9 on 2024-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_reminder', '0005_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_sent_period',
            field=models.IntegerField(default=0),
        ),
    ]
