# Generated by Django 4.2.9 on 2024-03-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_reminder', '0007_remove_user_last_sent_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='last_sent_time',
        ),
    ]
